name: flutter_news
description: A Hacker News client in flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: '^0.4.0'
  timeago: '^1.2.0'
  shared_preferences:
  intl: 0.15.1
  html_unescape: '^0.1.5'

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data/askstories.json
    - assets/mock_data/beststories.json
    - assets/mock_data/jobstories.json
    - assets/mock_data/newstories.json
    - assets/mock_data/showstories.json
    - assets/mock_data/topstories.json
    # Stories
    - assets/mock_data/14411126.json
    - assets/mock_data/14410533.json
    - assets/mock_data/14411067.json
    - assets/mock_data/14411499.json
    - assets/mock_data/14409760.json
    - assets/mock_data/14411297.json
    - assets/mock_data/14408859.json
    - assets/mock_data/14406874.json
    - assets/mock_data/14409553.json
    - assets/mock_data/14411338.json
    - assets/mock_data/14410489.json
    - assets/mock_data/14410201.json
    - assets/mock_data/14410846.json
    - assets/mock_data/14409534.json
    - assets/mock_data/14409269.json
    - assets/mock_data/14405179.json
    - assets/mock_data/14410357.json
    - assets/mock_data/14409019.json
    - assets/mock_data/14409210.json
    - assets/mock_data/14403911.json
    - assets/mock_data/14411150.json
    - assets/mock_data/14409797.json
    - assets/mock_data/14407207.json
    - assets/mock_data/14407393.json
    - assets/mock_data/14409950.json
    # Comments
    - assets/mock_data/14411458.json  # L1
    - assets/mock_data/14411669.json  #  L2
    - assets/mock_data/14411734.json  #   L3
    - assets/mock_data/14414333.json  #  L2
    - assets/mock_data/14411945.json  #  L2
    - assets/mock_data/14412016.json  #   L3
    - assets/mock_data/14413024.json  #    L4
    - assets/mock_data/14411398.json  # L1
    - assets/mock_data/14411502.json  #  L2
    - assets/mock_data/14411508.json  #  L2
    - assets/mock_data/14411452.json  #  L2
    - assets/mock_data/14411496.json  #  L2
    - assets/mock_data/14411463.json  #  L2
    - assets/mock_data/14411443.json  #  L2
    - assets/mock_data/14412239.json  #  L2
    - assets/mock_data/14411892.json  #  L2
    - assets/mock_data/14411594.json  # L1
    - assets/mock_data/14412057.json  # L1
    - assets/mock_data/14411204.json  # L1
    - assets/mock_data/14411534.json  # L1
    - assets/mock_data/14411440.json  # L1
    - assets/mock_data/14411841.json  # L1
    - assets/mock_data/14411465.json  # L1
    - assets/mock_data/14411428.json  # L1
    - assets/mock_data/14411656.json  # L1
    - assets/mock_data/14411970.json  # L1
    - assets/mock_data/14411920.json  # L1
    - assets/mock_data/14411794.json  # L1
    - assets/mock_data/14411472.json  # L1
    - assets/mock_data/14411752.json  # L1
    - assets/mock_data/14411775.json  # L1 deleted
    - assets/mock_data/14411510.json  # L1
    - assets/mock_data/14411789.json  # L1
    - assets/mock_data/14411512.json  # L1
    - assets/mock_data/14411710.json  # L1
